/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ims.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author NAT
 */
public class EmployeeList extends javax.swing.JFrame {
      static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/employee";
    static final String USER = "root";
    static final String PASS = "";
    int H;
    String shcc;
    
    public String edit;
    String KH= "1";
    public String SHCC2; public String ho2; public String ten2; public String hovaten2;public String tengoikhac2;
    public String gioitinh2; public String ngaysinh2; public String noisinh2; public String socmnd2; public String ngaycap2;
    public String noicap2; public String dtdd2; public String dtnr2; public String email2; public String dantoc2;
    public String tongiao2; public String quoctich2; public String tthonnhan2; public String quequan2;
    public  String dctt2; public String noht2; public String ghichu2; public String donvi2; public String daibieu2; 
    public String loainhansu2; public String bienche2; public String ngaytdkhd2; public String ngaybng2; public String chucdanh2;
    public String chucvu2; public String chieucao2; public String cannang2; public String nhommau2; 
    public String trinhtrangsuckhoe2; public String thanhphanxuatthan2; public String uutiengiadinh2;
    public String uutienbanthan2; public String nguontuyendung2; public String ngaytuyendung2;
    
    String id1;
    EmployeeBLL bll = new EmployeeBLL();
    /** Creates new form EmployeeList */
    public EmployeeList() {
        initComponents();
        setInfoDialog();
    }
    public  void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);        
        setResizable(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btsua = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tbxoa = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btNew.setText("Thêm ");
        btNew.setFocusable(false);
        btNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btNew);
        jToolBar1.add(jSeparator1);

        btsua.setText("Sửa");
        btsua.setFocusable(false);
        btsua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btsua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });
        jToolBar1.add(btsua);
        jToolBar1.add(jSeparator2);

        tbxoa.setText("Xóa");
        tbxoa.setFocusable(false);
        tbxoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbxoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxoaActionPerformed(evt);
            }
        });
        jToolBar1.add(tbxoa);
        jToolBar1.add(jSeparator3);

        jButton4.setText("In");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        jButton5.setText("Thoát");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 25));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Số hiệu công chức", "Họ", "Tên", "Họ và tên", "Tên gọi khác", "Giới tính", "Ngày sinh", "Nơi sinh", "Số CMND", "Ngày cấp", "Nơi Cấp", "ĐTi di động", "ĐT nhà riêng", "Email", "Dân tộc", "Tôn giáo", "Quốc tịch", "TTHN", "Quê quán", "ĐCTT", "NOHN", "Ghi chú", "Đơn vị", "Đại biểu", "LNS", "Biên chế", "Ngày TD/KHĐ", "Ngày BNG", "Chức danh", "Chức vụ", "Chiều cao", "Cân nặng", "Nhóm máu", "TTSK", "TPXT", "UTGD", "UTBT", "Nguôn TD", "Ngày TD"
            }
        ));
        table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableFocusGained(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1360, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        Employee emGui= new Employee();
        emGui.setVisible(true);
    }//GEN-LAST:event_btNewActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        Employee emGui= new Employee();
        int row = table.getSelectedRow();
        String shcc2 = table.getModel().getValueAt(row, 0).toString();
        String ho = table.getModel().getValueAt(row, 1).toString();    
        String ten = table.getModel().getValueAt(row, 2).toString();  
        String hovaten = table.getModel().getValueAt(row, 3).toString(); 
        String tengoikhac = table.getModel().getValueAt(row, 4).toString();    
        String gioitinh = table.getModel().getValueAt(row, 5).toString(); 
        String ngaysinh = table.getModel().getValueAt(row, 6).toString();  
        String noisinh = table.getModel().getValueAt(row, 7).toString();  
        String socmnd = table.getModel().getValueAt(row, 8).toString();    
        String ngaycap = table.getModel().getValueAt(row, 9).toString();  
        String noicap = table.getModel().getValueAt(row, 10).toString();  
        String dtdd = table.getModel().getValueAt(row, 11).toString();   
        String dtnr = table.getModel().getValueAt(row, 12).toString();     
        String email = table.getModel().getValueAt(row, 13).toString();   
        String dantoc = table.getModel().getValueAt(row, 14).toString();  
        String tongiao = table.getModel().getValueAt(row, 15).toString();  
        String quoctich = table.getModel().getValueAt(row, 16).toString(); 
        String tthonnhan = table.getModel().getValueAt(row, 17).toString();   
        String quequan = table.getModel().getValueAt(row, 18).toString();  
        String dctt = table.getModel().getValueAt(row, 19).toString();    
        String noht = table.getModel().getValueAt(row, 20).toString();    
        String ghichu = table.getModel().getValueAt(row, 21).toString();  
        String donvi = table.getModel().getValueAt(row, 22).toString();   
        String daibieu = table.getModel().getValueAt(row, 23).toString(); 
        String loainhansu = table.getModel().getValueAt(row, 24).toString();   
        String bienche = table.getModel().getValueAt(row, 25).toString();     
        String ngaytdkhd = table.getModel().getValueAt(row, 26).toString();   
        String ngaybng = table.getModel().getValueAt(row, 27).toString();      
        String chucdanh = table.getModel().getValueAt(row, 28).toString();    
        String chucvu = table.getModel().getValueAt(row, 29).toString();       
        String chieucao = table.getModel().getValueAt(row, 30).toString();     
        String cannang = table.getModel().getValueAt(row, 31).toString();      
        String nhommau = table.getModel().getValueAt(row, 32).toString();     
        String trinhtrangsuckhoe = table.getModel().getValueAt(row, 33).toString(); 
        String thanhphanxuatthan = table.getModel().getValueAt(row, 34).toString();   
        String uutiengiadinh = table.getModel().getValueAt(row, 35).toString();    
        String uutienbanthan = table.getModel().getValueAt(row, 36).toString();    
        String nguontuyendung = table.getModel().getValueAt(row, 37).toString();  
        String ngaytuyendung = table.getModel().getValueAt(row, 38).toString();   
        emGui.txtsohieucongchuc.setText(shcc2);
        emGui.txtho.setText(ho);
        emGui.txtten.setText(ten);
        emGui.txthovaten.setText(hovaten);
        emGui.txttengoikhac.setText(tengoikhac);
        emGui.txtgioitinh.setSelectedItem(gioitinh);
        //emGui.txtngaysinh.setDate(ngaysinh);
        
        emGui.txtnoisinh.setText(noisinh);
        emGui.txtsocmnd.setText(socmnd);
       // emGui.txtngaycap.setText(ngaycap);
        emGui.txtnoicap.setSelectedItem(noicap);
        emGui.txtdonvi.setSelectedItem(donvi);
//        if(daibieu == "Đại biểu quốc hội"){
//            emGui.cb1.isSelected(true);
//        }
      
        emGui.txtloainhansu.setSelectedItem(loainhansu);
        
        //emGui.txtsohieucongchuc.setTexdt(bienche);
        
       // emGui.txtho.setText(ngaytdkhd);
        //emGui.txtsohieucongchuc.setText(ngaybng);
        
        emGui.txtchucdanh.setSelectedItem(chucdanh);
        emGui.txtchucvu.setSelectedItem(chucvu);
        emGui.txtdienthoaididong.setText(dtdd);
        emGui.txtdienthoainharieng.setText(dtnr);
        emGui.txtemail.setText(email);
        emGui.txtdantoc.setSelectedItem(dantoc);
        emGui.txttongiao.setSelectedItem(tongiao);
        emGui.txtquoctich.setSelectedItem(quoctich);
        emGui.txttrinhtranghonnhan.setSelectedItem(tthonnhan);
        emGui.txtquequan.setText(quequan);
        emGui.txtdiachithuongtru.setText(dctt);
        emGui.txtnoiohiennay.setText(noht);
        emGui.txtghichu.setText(ghichu);
        int chieucao2 = Integer.parseInt(chieucao);
        emGui.txtchieucao.setValue(chieucao2);
        int cannang2 = Integer.parseInt(cannang);
        emGui.txtcannang.setValue(cannang2);
        emGui.txtnhommau.setSelectedItem(nhommau);
        emGui.txttinhtrangsuckhoe.setSelectedItem(trinhtrangsuckhoe);
        emGui.txtthanhphanxuatthan.setSelectedItem(thanhphanxuatthan);
        emGui.txtuutiengiadinh.setSelectedItem(uutiengiadinh);
        emGui.txtuutienbanthan.setSelectedItem(uutienbanthan);
        emGui.txtnguontuyendung.setText(nguontuyendung);
      //  emGui.txtngaytuyendung.setText(ngaytuyendung);
        


     
    }//GEN-LAST:event_tableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         ResultSet rs = bll.readEmployee();
        int row = 0;
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[0]);
                model.setValueAt(rs.getString("nhanvien.SHCC"), row, 0);
                model.setValueAt(rs.getString("nhanvien.ho"), row, 1);
                model.setValueAt(rs.getString("nhanvien.ten"), row, 2);
                model.setValueAt(rs.getString("nhanvien.hovaten"), row, 3);
                model.setValueAt(rs.getString("nhanvien.tengoikhac"), row, 4);
                model.setValueAt(rs.getString("nhanvien.gioitinh"), row, 5);
                model.setValueAt(rs.getString("nhanvien.ngaysinh"), row, 6);
                model.setValueAt(rs.getString("nhanvien.noisinh"), row, 7);
                model.setValueAt(rs.getString("nhanvien.socmnd"), row, 8);
                model.setValueAt(rs.getString("nhanvien.ngaycap"), row, 9);
                model.setValueAt(rs.getString("nhanvien.noicap"), row, 10);
                model.setValueAt(rs.getString("nhanvien.dtdd"), row, 11);
                model.setValueAt(rs.getString("nhanvien.dtnr"), row, 12);
                model.setValueAt(rs.getString("nhanvien.email"), row, 13);
                model.setValueAt(rs.getString("nhanvien.dantoc"), row, 14);
                model.setValueAt(rs.getString("nhanvien.tongiao"), row, 15);
                model.setValueAt(rs.getString("nhanvien.quoctich"), row, 16);
                model.setValueAt(rs.getString("nhanvien.tthonnhan"), row, 17);
                model.setValueAt(rs.getString("nhanvien.quequan"), row, 18);
                model.setValueAt(rs.getString("nhanvien.dctt"), row, 19);
                model.setValueAt(rs.getString("nhanvien.noht"), row, 20);
                model.setValueAt(rs.getString("nhanvien.ghichu"), row, 21);
                model.setValueAt(rs.getString("nhanvien.donvi"), row, 22);
                model.setValueAt(rs.getString("nhanvien.daibieu"), row, 23);
                model.setValueAt(rs.getString("nhanvien.loainhansu"), row, 24);
                model.setValueAt(rs.getString("nhanvien.bienche"), row, 25);
                model.setValueAt(rs.getString("nhanvien.ngaytdkhd"), row, 26);
                model.setValueAt(rs.getString("nhanvien.ngaybng"), row, 27);
                model.setValueAt(rs.getString("nhanvien.chucdanh"), row, 28);
                model.setValueAt(rs.getString("nhanvien.chucvu"), row, 29);
                model.setValueAt(rs.getString("nhanvien.chieucao"), row, 30);
                model.setValueAt(rs.getString("nhanvien.cannang"), row, 31);
                model.setValueAt(rs.getString("nhanvien.nhommau"), row, 32);
                model.setValueAt(rs.getString("nhanvien.trinhtrangsuckhoe"), row, 33);
                model.setValueAt(rs.getString("nhanvien.thanhphanxuatthan"), row, 34);
                model.setValueAt(rs.getString("nhanvien.uutiengiadinh"), row, 35);
                model.setValueAt(rs.getString("nhanvien.uutienbanthan"), row, 36);
                model.setValueAt(rs.getString("nhanvien.nguontuyendung"), row, 37);
                model.setValueAt(rs.getString("nhanvien.ngaytuyendung"), row, 38);
            
                row++;
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        Employee emGui= new Employee();
        int row = table.getSelectedRow();
        String shcc2 = table.getModel().getValueAt(row, 0).toString();
        String ho = table.getModel().getValueAt(row, 1).toString();    
        String ten = table.getModel().getValueAt(row, 2).toString();  
        String hovaten = table.getModel().getValueAt(row, 3).toString(); 
        String tengoikhac = table.getModel().getValueAt(row, 4).toString();    
        String gioitinh = table.getModel().getValueAt(row, 5).toString(); 
        String ngaysinh = table.getModel().getValueAt(row, 6).toString();  
        String noisinh = table.getModel().getValueAt(row, 7).toString();  
        String socmnd = table.getModel().getValueAt(row, 8).toString();    
        String ngaycap = table.getModel().getValueAt(row, 9).toString();  
        String noicap = table.getModel().getValueAt(row, 10).toString();  
        String dtdd = table.getModel().getValueAt(row, 11).toString();   
        String dtnr = table.getModel().getValueAt(row, 12).toString();     
        String email = table.getModel().getValueAt(row, 13).toString();   
        String dantoc = table.getModel().getValueAt(row, 14).toString();  
        String tongiao = table.getModel().getValueAt(row, 15).toString();  
        String quoctich = table.getModel().getValueAt(row, 16).toString(); 
        String tthonnhan = table.getModel().getValueAt(row, 17).toString();   
        String quequan = table.getModel().getValueAt(row, 18).toString();  
        String dctt = table.getModel().getValueAt(row, 19).toString();    
        String noht = table.getModel().getValueAt(row, 20).toString();    
        String ghichu = table.getModel().getValueAt(row, 21).toString();  
        String donvi = table.getModel().getValueAt(row, 22).toString();   
        String daibieu = table.getModel().getValueAt(row, 23).toString(); 
        String loainhansu = table.getModel().getValueAt(row, 24).toString();   
        String bienche = table.getModel().getValueAt(row, 25).toString();     
        String ngaytdkhd = table.getModel().getValueAt(row, 26).toString();   
        String ngaybng = table.getModel().getValueAt(row, 27).toString();      
        String chucdanh = table.getModel().getValueAt(row, 28).toString();    
        String chucvu = table.getModel().getValueAt(row, 29).toString();       
        String chieucao = table.getModel().getValueAt(row, 30).toString();     
        String cannang = table.getModel().getValueAt(row, 31).toString();      
        String nhommau = table.getModel().getValueAt(row, 32).toString();     
        String trinhtrangsuckhoe = table.getModel().getValueAt(row, 33).toString(); 
        String thanhphanxuatthan = table.getModel().getValueAt(row, 34).toString();   
        String uutiengiadinh = table.getModel().getValueAt(row, 35).toString();    
        String uutienbanthan = table.getModel().getValueAt(row, 36).toString();    
        String nguontuyendung = table.getModel().getValueAt(row, 37).toString();  
        String ngaytuyendung = table.getModel().getValueAt(row, 38).toString();   
        emGui.txtsohieucongchuc.setText(shcc2);
        emGui.txtho.setText(ho);
        emGui.txtten.setText(ten);
        emGui.txthovaten.setText(hovaten);
        emGui.txttengoikhac.setText(tengoikhac);
        emGui.txtgioitinh.setSelectedItem(gioitinh);
        //emGui.txtngaysinh.setDate(ngaysinh);
        emGui.txtnoisinh.setText(noisinh);
        emGui.txtsocmnd.setText(socmnd);
       // emGui.txtngaycap.setText(ngaycap);
        emGui.txtnoicap.setSelectedItem(noicap);
        emGui.txtdonvi.setSelectedItem(donvi);
//        if(daibieu == "Đại biểu quốc hội"){
//            emGui.cb1.isSelected(true);
//        }
      
        emGui.txtloainhansu.setSelectedItem(loainhansu);
        
        //emGui.txtsohieucongchuc.setTexdt(bienche);
        
       // emGui.txtngaytuyendungkyhopdong.setText(ngaytdkhd);
        //emGui.txtsohieucongchuc.setText(ngaybng);
        
        emGui.txtchucdanh.setSelectedItem(chucdanh);
        emGui.txtchucvu.setSelectedItem(chucvu);
        emGui.txtdienthoaididong.setText(dtdd);
        emGui.txtdienthoainharieng.setText(dtnr);
        emGui.txtemail.setText(email);
        emGui.txtdantoc.setSelectedItem(dantoc);
        emGui.txttongiao.setSelectedItem(tongiao);
        emGui.txtquoctich.setSelectedItem(quoctich);
        emGui.txttrinhtranghonnhan.setSelectedItem(tthonnhan);
        emGui.txtquequan.setText(quequan);
        emGui.txtdiachithuongtru.setText(dctt);
        emGui.txtnoiohiennay.setText(noht);
        emGui.txtghichu.setText(ghichu);
         int chieucao2 = Integer.parseInt(chieucao);
        emGui.txtchieucao.setValue(chieucao2);
        int cannang2 = Integer.parseInt(cannang);
        emGui.txtcannang.setValue(cannang2);
        emGui.txtnhommau.setSelectedItem(nhommau);
        emGui.txttinhtrangsuckhoe.setSelectedItem(trinhtrangsuckhoe);
        emGui.txtthanhphanxuatthan.setSelectedItem(thanhphanxuatthan);
        emGui.txtuutiengiadinh.setSelectedItem(uutiengiadinh);
        emGui.txtuutienbanthan.setSelectedItem(uutienbanthan);
        emGui.txtnguontuyendung.setText(nguontuyendung);
      //  emGui.txtngaytuyendung.setText(ngaytuyendung);
        
        H = 1;
       // Employee emGui= new Employee();
        emGui.setVisible(true);
      
        
                
    }//GEN-LAST:event_btsuaActionPerformed

    private void tbxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxoaActionPerformed
         String id = shcc;
        try {
            bll.deleteEmployee(id);
        } catch (Exception ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        int row = table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.removeRow(row);
    }//GEN-LAST:event_tbxoaActionPerformed

    private void tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableFocusGained
    ResultSet rs = bll.readEmployee();
        int row = 0;
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[0]);
                model.setValueAt(rs.getString("nhanvien.SHCC"), row, 0);
                model.setValueAt(rs.getString("nhanvien.ho"), row, 1);
                model.setValueAt(rs.getString("nhanvien.ten"), row, 2);
                model.setValueAt(rs.getString("nhanvien.hovaten"), row, 3);
                model.setValueAt(rs.getString("nhanvien.tengoikhac"), row, 4);
                model.setValueAt(rs.getString("nhanvien.gioitinh"), row, 5);
                model.setValueAt(rs.getString("nhanvien.ngaysinh"), row, 6);
                model.setValueAt(rs.getString("nhanvien.noisinh"), row, 7);
                model.setValueAt(rs.getString("nhanvien.socmnd"), row, 8);
                model.setValueAt(rs.getString("nhanvien.ngaycap"), row, 9);
                model.setValueAt(rs.getString("nhanvien.noicap"), row, 10);
                model.setValueAt(rs.getString("nhanvien.dtdd"), row, 11);
                model.setValueAt(rs.getString("nhanvien.dtnr"), row, 12);
                model.setValueAt(rs.getString("nhanvien.email"), row, 13);
                model.setValueAt(rs.getString("nhanvien.dantoc"), row, 14);
                model.setValueAt(rs.getString("nhanvien.tongiao"), row, 15);
                model.setValueAt(rs.getString("nhanvien.quoctich"), row, 16);
                model.setValueAt(rs.getString("nhanvien.tthonnhan"), row, 17);
                model.setValueAt(rs.getString("nhanvien.quequan"), row, 18);
                model.setValueAt(rs.getString("nhanvien.dctt"), row, 19);
                model.setValueAt(rs.getString("nhanvien.noht"), row, 20);
                model.setValueAt(rs.getString("nhanvien.ghichu"), row, 21);
                model.setValueAt(rs.getString("nhanvien.donvi"), row, 22);
                model.setValueAt(rs.getString("nhanvien.daibieu"), row, 23);
                model.setValueAt(rs.getString("nhanvien.loainhansu"), row, 24);
                model.setValueAt(rs.getString("nhanvien.bienche"), row, 25);
                model.setValueAt(rs.getString("nhanvien.ngaytdkhd"), row, 26);
                model.setValueAt(rs.getString("nhanvien.ngaybng"), row, 27);
                model.setValueAt(rs.getString("nhanvien.chucdanh"), row, 28);
                model.setValueAt(rs.getString("nhanvien.chucvu"), row, 29);
                model.setValueAt(rs.getString("nhanvien.chieucao"), row, 30);
                model.setValueAt(rs.getString("nhanvien.cannang"), row, 31);
                model.setValueAt(rs.getString("nhanvien.nhommau"), row, 32);
                model.setValueAt(rs.getString("nhanvien.trinhtrangsuckhoe"), row, 33);
                model.setValueAt(rs.getString("nhanvien.thanhphanxuatthan"), row, 34);
                model.setValueAt(rs.getString("nhanvien.uutiengiadinh"), row, 35);
                model.setValueAt(rs.getString("nhanvien.uutienbanthan"), row, 36);
                model.setValueAt(rs.getString("nhanvien.nguontuyendung"), row, 37);
                model.setValueAt(rs.getString("nhanvien.ngaytuyendung"), row, 38);
            
                row++;
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_tableFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNew;
    private javax.swing.JButton btsua;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable table;
    private javax.swing.JButton tbxoa;
    // End of variables declaration//GEN-END:variables

}
